### ISSUE TITLE
Needs a windows installer

### ISSUE THREAD

**Issue by Bavfalcon9** [McthamRewrite/SUSDDOS#1]
I see you have install.sh, but where is install.ps1?

**Comment by pooooooon** [comment]
Bruh @PC1266

**Comment by PC1266** [comment]
@Bavfalcon9 Right. Please wait for a new update soon!
but not long, just 1-2 days!

**Comment by PC1266** [comment]
@Bavfalcon9 https://github.com/McthamRewrite/SUSDDOS/releases/tag/WinInstallers
